### ISSUE TITLE
Clarify replaces chain requirement for building channels

### ISSUE THREAD

**Issue by joelanford** [operator-framework/olm-docs#223]
> The entry specifying the `skipRange` will be presented as a direct (one hop) update to any version from that package within that range. The versions in this range **do not need to be in the catalog** in order for bundle addition to be successful.

(i.e. "but could be" -- nothing is mentioned about still requiring a linear replaces chain)

It would be useful if the documentation mentioned that `replaces` is still required with `skipRange` when there is more than one version. Compare this to the example used for the "Skips" section, which includes the replaces field even though the catalog does not contain `myoperator.v1.0.0`:
```yaml
  - name: myoperator.v1.0.3
    replaces: myoperator.v1.0.0
    skips:
      - myoperator.v1.0.1
      - myoperator.v1.0.2
```

Perhaps the "SkipRange" example should be
```yaml
  - name: myoperator.v1.0.3
    replaces: myoperator.v1.0.0
    skipRange: ">=1.0.0 <1.0.3"
```
to match.

_Originally posted by @amisevsk in https://github.com/operator-framework/operator-registry/issues/822#issuecomment-1018687671_
