### ISSUE TITLE
Creating a Catalog of operators

### ISSUE THREAD

**Issue by thomassuedbroecker** [operator-framework/olm-docs#233]
## Version

I have the same behavior on both OS.

* macOS

```sh
opm version
Version: version.Version{OpmVersion:"v1.21.0", GitCommit:"9999f796", BuildDate:"2022-03-03T21:23:12Z", GoOs:"linux", GoArch:"amd64"}
```

* Linux:

```sh
opm version
Version: version.Version{OpmVersion:"v1.21.0", GitCommit:"9999f796", BuildDate:"2022-03-03T21:23:12Z", GoOs:"linux", GoArch:"amd64"}
```

### Situation

I try follow the instruction to [create a catalog in the OLM documention](https://olm.operatorframework.io/docs/tasks/creating-a-catalog/) 

### Initialize the catalog (https://olm.operatorframework.io/docs/tasks/creating-a-catalog/#initialize-the-catalog)

This are the steps to reproduce:

### Step 1:  Execute `opm alpha generate`

```sh
opm alpha generate dockerfile frontend-catalog
```

The creation of the dockerfile doesn't work

* Output

```sh
Run an alpha subcommand

Usage:
  opm alpha [command]

Available Commands:
  bundle      Operator bundle commands
  diff        Diff old and new catalog references into a declarative config
  list        List contents of an index

Flags:
  -h, --help   help for alpha

Global Flags:
      --skip-tls-verify   skip TLS certificate verification for container image registries while pulling bundles
      --use-http          use plain HTTP for container image registries while pulling bundles

Use "opm alpha [command] --help" for more information about a command.
```

### Step 2:  Execute `opm init`

The creation operator yaml or json works

```sh
opm init frontendoperator \
    --default-channel=preview \
    --description=./frontend-catalog/README.md \
    --icon=./frontend-catalog/frontendoperator.svg \
    --output yaml > ./frontend-catalog/operator.yaml
```

* Output:

```yaml
---
defaultChannel: preview
description: |-
  # This is an example Operator

  You will just deploy a simple web application.
icon:
  base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbm........m9ybT0icm90YXRlKDQ1KSIgLz4KPC9zdmc+Cg==
  mediatype: image/svg+xml
name: frontendoperator
schema: olm.package
```

### Step 3:  Execute `opm validate`

Doesn't work

```sh
opm validate frontend-catalog
```

Output:

```sh
FATA[0000] json: cannot unmarshal string into Go value of type declcfg.tmp 
```

### Summary

For me the OPM doesn't work on two OSs, I am not able to follow the written documentation.
