### ISSUE TITLE
Update Arbitrary Properties example on the Dependency Resolution page

### ISSUE THREAD

**Issue by nschambu** [operator-framework/olm-docs#271]
Issue: The example in the Arbitrary Properties section of the Dependency Resolution page is incorrect.
Page in question: https://olm.operatorframework.io/docs/concepts/olm-architecture/dependency-resolution/#arbitrary-properties

**Details**

The Arbitrary Properties section of the Dependency Resolution page includes an additional "property" field that is unnecessary. 

Current example:

```yaml
properties:
  - property:
      type: sushi
      value: salmon
  - property:
      type: soup
      value: miso
  - property:
      type: olm.gvk
      value:
        group: olm.coreos.io
        version: v1alpha1
        kind: bento
```

Proposed update:

```yaml
properties:
  - type: sushi
    value: salmon
  - type: soup
    value: miso
  - type: olm.gvk
    value:
      group: olm.coreos.io
      version: v1alpha1
      kind: bento
```

My dependency resolution was failing when using the current example, but was successful when I updated it to the proposed update.
